# Generated by Django 3.0.2 on 2020-02-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signal',
        ),
        migrations.DeleteModel(
            name='SignalCategory',
        ),
    ]
