# Generated by Django 3.0.2 on 2020-02-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20200202_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='manufacture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='components.Manufacture', unique=True),
        ),
    ]
