# Generated by Django 3.0.2 on 2020-02-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_historicalcomponent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalComponent',
        ),
    ]
