# Generated by Django 3.0.2 on 2020-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_historicalcomponent_historicalmanufacture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalManufacture',
        ),
    ]
