# Generated by Django 3.0.2 on 2020-02-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_delete_historicalmanufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='manufacture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='components.Manufacture'),
        ),
    ]
