# Generated by Django 3.0.2 on 2020-02-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_historicalmanufacture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanufacture',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalComponent',
        ),
        migrations.DeleteModel(
            name='HistoricalManufacture',
        ),
    ]
