# Generated by Django 3.0.2 on 2020-02-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemarchitectures', '0005_auto_20200205_2021'),
        ('components', '0010_auto_20200207_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='systemarchitectures.System'),
        ),
    ]
