# Generated by Django 3.0.2 on 2020-02-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20200207_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='component',
            name='name',
        ),
        migrations.AlterField(
            model_name='component',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.Manufacture'),
        ),
    ]
