# Generated by Django 3.0.2 on 2020-02-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemarchitectures', '0006_auto_20200208_0955'),
        ('projects', '0008_auto_20200207_2332'),
        ('components', '0013_auto_20200208_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='componentclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='components.ComponentClass'),
        ),
        migrations.AddField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='component',
            name='system',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='systemarchitectures.System'),
        ),
    ]
