# Generated by Django 3.0.2 on 2020-02-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200207_2332'),
        ('systemarchitectures', '0006_auto_20200208_0955'),
        ('components', '0014_auto_20200208_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('components', models.ManyToManyField(blank=True, null=True, to='components.Component')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pidiagram', to='projects.Project')),
                ('system', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pidiagram', to='systemarchitectures.System')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PiComponent',
        ),
    ]
