# Generated by Django 3.0.2 on 2020-02-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200207_2332'),
        ('systemarchitectures', '0006_auto_20200208_0955'),
        ('components', '0015_auto_20200208_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picomponent', to='projects.Project')),
                ('system', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='picomponent', to='systemarchitectures.System', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='component',
            name='name',
        ),
        migrations.DeleteModel(
            name='PiDiagram',
        ),
        migrations.AddField(
            model_name='component',
            name='picomponent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='components.PiComponent'),
        ),
    ]
