# Generated by Django 3.0.2 on 2020-02-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_auto_20200209_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='picomponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='components.PiComponent'),
        ),
    ]
