# Generated by Django 3.0.2 on 2020-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_auto_20200209_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='picomponent',
        ),
        migrations.AddField(
            model_name='component',
            name='picomponent',
            field=models.ManyToManyField(to='components.PiComponent'),
        ),
    ]
