# Generated by Django 3.0.2 on 2020-02-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_auto_20200209_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picomponent',
            old_name='picomponent',
            new_name='components',
        ),
    ]
