# Generated by Django 3.0.2 on 2020-02-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_auto_20200209_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picomponent',
            name='components',
        ),
        migrations.AddField(
            model_name='picomponent',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='components.Component'),
        ),
    ]
