# Generated by Django 3.0.2 on 2020-02-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemarchitectures', '0006_auto_20200208_0955'),
        ('components', '0021_auto_20200209_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picomponent',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='picomponent', to='systemarchitectures.System'),
        ),
    ]
