# Generated by Django 3.0.2 on 2020-02-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200207_2332'),
        ('components', '0022_auto_20200209_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picomponent',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='picomponent', to='projects.Project'),
        ),
    ]
