# Generated by Django 3.0.2 on 2020-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkarchitectures', '0002_historicalnetworkarchitecture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalNetworkArchitecture',
        ),
    ]
