# Generated by Django 3.0.2 on 2020-02-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('bustype', models.CharField(choices=[('EtherCAT', 'EtherCAT'), ('PROFINET', 'PROFINET ')], default='EtherCAT', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('samplerate', models.IntegerField()),
                ('bustype', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='interfaces.BusType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
