# Generated by Django 3.0.2 on 2020-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_historicalbustype_historicalinterface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinterface',
            name='bustype',
        ),
        migrations.RemoveField(
            model_name='historicalinterface',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalBusType',
        ),
        migrations.DeleteModel(
            name='HistoricalInterface',
        ),
    ]
