# Generated by Django 3.0.2 on 2020-02-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0003_auto_20200205_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='bustype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='interfaces.BusType'),
        ),
    ]
