# Generated by Django 3.0.2 on 2020-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('signal_name_style', models.CharField(choices=[('CC', 'camelCase'), ('US', 'underscore')], default='US', max_length=200)),
                ('signal_name_concatenation', models.CharField(choices=[('SCSNCN', 'signal class + signal name + component name'), ('SCCNSN', 'signal class + component name + signal name')], default='SCSNCN', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
