# Generated by Django 3.0.2 on 2020-02-06 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preferences', '0003_delete_generalpreferences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalProjectPreferences',
            new_name='HistoricalProjectPreference',
        ),
        migrations.RenameModel(
            old_name='ProjectPreferences',
            new_name='ProjectPreference',
        ),
        migrations.AlterModelOptions(
            name='historicalprojectpreference',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project preference'},
        ),
    ]
