# Generated by Django 3.0.2 on 2020-02-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20200206_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProjectPreference',
        ),
    ]
