# Generated by Django 3.0.2 on 2020-02-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='systems', to='projects.Project')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='systemarchitectures.System')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
