# Generated by Django 3.0.2 on 2020-02-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemarchitectures', '0002_auto_20200202_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='systemarchitectures.System'),
        ),
        migrations.AlterField(
            model_name='system',
            name='systemtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='systemarchitectures.SystemType', unique=True),
        ),
    ]
