# Generated by Django 3.0.2 on 2020-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemarchitectures', '0004_historicalsystem_historicalsystemtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsystemtype',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalSystem',
        ),
        migrations.DeleteModel(
            name='HistoricalSystemType',
        ),
    ]
