# Generated by Django 3.0.2 on 2020-02-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemarchitectures', '0005_auto_20200205_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='systemtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='systemarchitectures.SystemType'),
        ),
    ]
