# Generated by Django 3.0.2 on 2020-02-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0002_auto_20200202_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('component', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='components.Component')),
                ('signalcategory', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='signals.SignalCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
