# Generated by Django 3.0.2 on 2020-02-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_signal_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='signalcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='signals.SignalCategory', unique=True),
        ),
    ]
