# Generated by Django 3.0.2 on 2020-02-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0001_initial'),
        ('signals', '0003_auto_20200205_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='datatype',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='datatypes.DataType', unique=True),
        ),
    ]
