# Generated by Django 3.0.2 on 2020-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_historicalsignal_historicalsignalcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsignalcategory',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalSignal',
        ),
        migrations.DeleteModel(
            name='HistoricalSignalCategory',
        ),
    ]
