# Generated by Django 3.0.2 on 2020-02-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0003_delete_historicaldatatype'),
        ('signals', '0006_auto_20200205_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='datatype',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='datatypes.DataType'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='signalcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='signals.SignalCategory'),
        ),
    ]
