# Generated by Django 3.0.2 on 2020-02-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0003_auto_20200205_2021'),
        ('signals', '0008_historicalsignal_historicalsignalcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsignal',
            name='interface',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='interfaces.Interface'),
        ),
        migrations.AddField(
            model_name='signal',
            name='interface',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='interfaces.Interface'),
        ),
    ]
