# Generated by Django 3.0.2 on 2020-02-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0009_auto_20200206_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsignal',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='interface',
        ),
    ]
