# Generated by Django 3.0.2 on 2020-02-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_auto_20200206_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsignal',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='interface',
        ),
    ]
