# Generated by Django 3.0.2 on 2020-02-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_auto_20200207_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsignalcategory',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalSignal',
        ),
        migrations.DeleteModel(
            name='HistoricalSignalCategory',
        ),
    ]
