# Generated by Django 3.0.2 on 2020-02-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0014_auto_20200207_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAlarmLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('alias', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('autoreset', models.BooleanField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('lowervalue', models.FloatField(blank=True, null=True)),
                ('currentvalue', models.FloatField()),
                ('uppervalue', models.FloatField(blank=True, null=True)),
                ('lowerdelay', models.FloatField(blank=True, null=True)),
                ('currentdelay', models.FloatField(blank=True, null=True)),
                ('upperdelay', models.FloatField(blank=True, null=True)),
                ('signal', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signalalarm', to='signals.Signal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
