# Generated by Django 3.0.2 on 2020-02-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0023_auto_20200209_1816'),
        ('signals', '0015_projectalarmlevel_signalalarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalalarm',
            name='picomponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signal', to='components.Component'),
        ),
    ]
