# Generated by Django 3.0.2 on 2020-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemofunits', '0002_historicalnonsiunit_historicalsiunit_historicalunitprefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsiunit',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalunitprefix',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalNonSiUnit',
        ),
        migrations.DeleteModel(
            name='HistoricalSiUnit',
        ),
        migrations.DeleteModel(
            name='HistoricalUnitPrefix',
        ),
    ]
