# Generated by Django 3.0.2 on 2020-02-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('identification_number', models.DecimalField(decimal_places=0, max_digits=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='customer', to='customers.Customer', unique=True)),
                ('subcontractor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subcontractor', to='customers.Customer', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
