# Generated by Django 3.0.2 on 2020-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_historicalproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
    ]
