# Generated by Django 3.0.2 on 2020-02-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_historicalproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
    ]
