# Generated by Django 3.0.2 on 2020-02-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_historicalcustomer'),
        ('projects', '0007_delete_historicalproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subcontractor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor', to='customers.Customer'),
        ),
    ]
