# Generated by Django 3.0.2 on 2020-02-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('datatype', models.CharField(max_length=200)),
                ('memoryspace', models.IntegerField()),
                ('lowerbound', models.IntegerField()),
                ('upperbound', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
