# Generated by Django 3.0.2 on 2020-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0002_historicaldatatype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDataType',
        ),
    ]
